#index:
#    path: /
#    controller: App\Controller\DefaultController::index
companies:
  path: /companies
  controller: App\Controller\CompanyController::index

company_detail:
    path: /companies/detail/{id}
    controller: App\Controller\CompanyController::showCompany
    methods: [GET]